#!/bin/bash

#
# A nice TeX compiler that compiles things lots, and makes a pdf.

if [ $# -eq 0 ]
then
    echo "Usage: maketex [texfile]"
    exit 1
else
    fullfile=$1
fi

basefile=$(basename "$fullfile" .tex)

echo -e "\e[31m(\e[0m\e[32m>\e[0m\e[33m\"\e[0m\e[34m)\e[0m\e[35m>\e[0m \e[31m<\e[0m\e[32m(\e[0m\e[33m'\e[0m\e[34m-\e[0m\e[35m'\e[0m\e[36m)\e[0m\e[35m>\e[0m \e[31m<\e[0m\e[32m(\e[0m\e[33m\"\e[0m\e[34m<\e[0m\e[35m)\e[0m"
echo "------------------------"
echo Compiling "$basefile".tex

pdflatex -interaction nonstopmode "$basefile".tex > /dev/null 2>&1
pdflatex -interaction nonstopmode "$basefile".tex
bibtex "$basefile"
bibtex "$basefile" > /dev/null 2>&1
pdflatex -interaction nonstopmode "$basefile".tex > /dev/null 2>&1
pdflatex -interaction nonstopmode "$basefile".tex > /dev/null 2>&1

rmTeX
echo "------------------------"
echo -e "\e[31m(\e[0m\e[32m>\e[0m\e[33m\"\e[0m\e[34m)\e[0m\e[35m>\e[0m \e[31m<\e[0m\e[32m(\e[0m\e[33m'\e[0m\e[34m-\e[0m\e[35m'\e[0m\e[36m)\e[0m\e[35m>\e[0m \e[31m<\e[0m\e[32m(\e[0m\e[33m\"\e[0m\e[34m<\e[0m\e[35m)\e[0m"
#vim: cc=
